# Generated by Django 6.0.7 on 2026-08-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=16, unique=True)),
                ('phase', models.CharField(choices=[('hold', 'Hold'), ('description', 'Description'), ('verification', 'Verification'), ('verdict', 'Verdict'), ('decision', 'Decision'), ('reveal', 'Reveal')], default='hold', max_length=20)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_profile', models.CharField(choices=[('new', 'New'), ('established', 'Established'), ('hijacked', 'Hijacked')], max_length=20)),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text_headline', 'Text Headline'), ('composite', 'Composite')], max_length=20)),
                ('claim_category', models.CharField(choices=[('health_science', 'Health / Science'), ('finance_markets', 'Finance / Markets'), ('politics_elections', 'Politics / Elections'), ('environment_climate', 'Environment / Climate'), ('community_local', 'Community / Local')], max_length=30)),
                ('fabrication_type', models.CharField(choices=[('ai_generated', 'AI Generated'), ('outdated_recontextualized', 'Outdated / Recontextualized'), ('edited_authentic', 'Edited Authentic'), ('invented_narrative', 'Invented Narrative'), ('authentic', 'Authentic')], max_length=30)),
                ('deception_sophistication', models.CharField(choices=[('novice', 'Novice'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('image_url', models.URLField()),
                ('caption', models.TextField()),
                ('account_name', models.CharField(max_length=50)),
                ('handle', models.CharField(max_length=50)),
                ('follower_count', models.PositiveIntegerField()),
                ('verified_badge', models.BooleanField(default=False)),
                ('account_created_days_ago', models.PositiveIntegerField()),
                ('account_history', models.JSONField()),
                ('domain_authority', models.JSONField()),
                ('image_metadata', models.JSONField()),
                ('whois', models.JSONField()),
                ('cross_source', models.JSONField()),
                ('keyword_search', models.JSONField()),
                ('correct_verdict', models.CharField(choices=[('verified', 'Verified'), ('misleading', 'Misleading'), ('fabricated', 'Fabricated')], max_length=20)),
                ('ground_truth_explanation', models.TextField()),
                ('primary_verification_signal', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile (Scroller)'), ('desktop', 'Desktop (Verifier)')], max_length=10)),
                ('score', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('is_solo', models.BooleanField(default=False)),
                ('highest_error_verdict_type', models.CharField(blank=True, max_length=20, null=True)),
                ('most_used_tool', models.CharField(blank=True, max_length=30, null=True)),
                ('least_used_tool', models.CharField(blank=True, max_length=30, null=True)),
                ('avg_description_accuracy', models.FloatField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='api.room')),
                ('scroller_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scroller_rounds', to='api.player')),
                ('verifier_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifier_rounds', to='api.player')),
            ],
            options={
                'unique_together': {('room', 'round_number')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='current_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='api.scenario'),
        ),
        migrations.CreateModel(
            name='ScenarioAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict_chosen', models.CharField(choices=[('verified', 'Verified'), ('misleading', 'Misleading'), ('fabricated', 'Fabricated')], max_length=20)),
                ('confidence', models.PositiveSmallIntegerField()),
                ('checklist_account_name', models.BooleanField(default=False)),
                ('checklist_account_age', models.BooleanField(default=False)),
                ('checklist_post_type', models.BooleanField(default=False)),
                ('checklist_claim', models.BooleanField(default=False)),
                ('checklist_anomalies', models.BooleanField(default=False)),
                ('tools_used', models.JSONField(default=list)),
                ('followed_recommendation', models.BooleanField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('description_completeness', models.PositiveSmallIntegerField()),
                ('description_precision', models.PositiveSmallIntegerField()),
                ('description_neutrality', models.PositiveSmallIntegerField()),
                ('description_anomaly_awareness', models.PositiveSmallIntegerField()),
                ('score_scroller', models.PositiveIntegerField(blank=True, null=True)),
                ('score_verifier', models.PositiveIntegerField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.room')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='api.round')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.scenario')),
            ],
            options={
                'unique_together': {('room', 'scenario')},
            },
        ),
        migrations.CreateModel(
            name='VerdictRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('verified', 'Verified'), ('misleading', 'Misleading'), ('fabricated', 'Fabricated')], max_length=20)),
                ('primary_signal', models.TextField()),
                ('confidence', models.PositiveSmallIntegerField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.scenarioattempt')),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='api.player')),
            ],
        ),
    ]
