# Generated by Django 6.0.7 on 2026-08-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='folowing_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
