# Generated by Django 6.0.7 on 2026-08-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scenario_folowing_count_scenario_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='folowing_count',
            new_name='following_count',
        ),
    ]
