# Generated by Django 6.0.7 on 2026-08-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_folowing_count_scenario_following_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarioattempt',
            name='verdict_chosen',
            field=models.CharField(blank=True, choices=[('verified', 'Verified'), ('misleading', 'Misleading'), ('fabricated', 'Fabricated')], max_length=20, null=True),
        ),
    ]
